"""remake migrations

Revision ID: 13634d9e0417
Revises: 8fc6890eedd3
Create Date: 2024-05-01 19:11:46.226584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13634d9e0417'
down_revision = '8fc6890eedd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
