"""no relationships

Revision ID: 4c946d60a6a7
Revises: 96100b90570a
Create Date: 2024-04-27 14:59:10.330513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c946d60a6a7'
down_revision = '96100b90570a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_posts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('pay', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=16), nullable=False),
    sa.Column('job_type', sa.String(length=16), nullable=False),
    sa.Column('start_from_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_posts_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_posts_user_id'), ['user_id'], unique=False)

    op.create_table('skills_posts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('location', sa.String(length=16), nullable=False),
    sa.Column('job_type', sa.String(length=16), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skills_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skills_posts_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_skills_posts_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index('ix_posts_name')
        batch_op.drop_index('ix_posts_user_id')

    op.drop_table('posts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=32), nullable=False),
    sa.Column('pay', sa.INTEGER(), nullable=False),
    sa.Column('location', sa.VARCHAR(length=16), nullable=False),
    sa.Column('job_type', sa.VARCHAR(length=16), nullable=False),
    sa.Column('start_from_date', sa.DATE(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), nullable=False),
    sa.Column('description', sa.VARCHAR(length=256), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index('ix_posts_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_posts_name', ['name'], unique=False)

    with op.batch_alter_table('skills_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_posts_user_id'))
        batch_op.drop_index(batch_op.f('ix_skills_posts_name'))

    op.drop_table('skills_posts')
    with op.batch_alter_table('job_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_posts_user_id'))
        batch_op.drop_index(batch_op.f('ix_job_posts_name'))

    op.drop_table('job_posts')
    # ### end Alembic commands ###
