"""removed status

Revision ID: 84a1f693b698
Revises: 13634d9e0417
Create Date: 2024-05-15 19:51:07.750541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84a1f693b698'
down_revision = '13634d9e0417'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('post_type',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=16),
               existing_nullable=False)
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=32), nullable=True))
        batch_op.alter_column('post_type',
               existing_type=sa.String(length=16),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
