"""amodified message table

Revision ID: 8fc6890eedd3
Revises: 2d46578f721f
Create Date: 2024-05-01 15:26:49.837278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fc6890eedd3'
down_revision = '2d46578f721f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
