"""changed fromd display name to email

Revision ID: 96100b90570a
Revises: 3812c5278b91
Create Date: 2024-04-25 10:46:53.241796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96100b90570a'
down_revision = '3812c5278b91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=64), nullable=False))
        batch_op.drop_index('ix_users_username')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.drop_column('username')
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.VARCHAR(length=32), nullable=False))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=32), nullable=False))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index('ix_users_username', ['username'], unique=1)
        batch_op.drop_column('email')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
