"""fixing nullable allowed

Revision ID: cc1587ebbe2d
Revises: a75fbab4c89f
Create Date: 2024-04-27 15:27:57.825829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc1587ebbe2d'
down_revision = 'a75fbab4c89f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('pay',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('start_from_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
        batch_op.alter_column('start_from_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('pay',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
