
name: CI

on:
    push:
        branches:
            - Branch-Chris
    pull_request: 
        branches: 
            - main

jobs: 
    run-test:
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                python-version:
                   - "3.12"
                   - "3.11"
                   - "3.10"
                   - "3.9"
                   - "3.8"

        name: Test
        runs-on: ${{ matrix.os }}

        steps:
            - name:  Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with: 
                python-version: ${{ matrix.python-version }}

            - name: Install dependancies
              run:  |
                python -m pip install pytest 
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Run tests
              run: 
                pytest --disable-warnings --setup-show --cov=app --capture=sys -s
